Update prevent.yml

diff --git a/.github/workflows/prevent.yml b/.github/workflows/prevent.yml
--- a/.github/workflows/prevent.yml
+++ b/.github/workflows/prevent.yml
@@ -21,12 +21,12 @@ jobs:
           git config user.email "<>"
 
       - name: Pull with Rebase
-        run: git pull --rebase origin v2
+        run: git pull --rebase origin main
 
       - name: Push Changes
         run: |
-          git push -u origin v2 || echo "Push failed. Retrying..."
+          git push -u origin main || echo "Push failed. Retrying..."
           while [ $? -ne 0 ]; do
-            git pull --rebase origin v2
-            git push -u origin v2
+            git pull --rebase origin main
+            git push -u origin main
           done
